apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: static-site
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_connections_handled{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
          service: {resource: "service"}
      name:
        matches: "^(.*)_handled"
        as: "${1}_per_second"
      metricsQuery: 'rate(<<.Series>>{<<.LabelMatchers>>}[2m])'
