apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: static-site
  labels:
    app: frontend
spec:
  lookupPolicy:
    local: false
  tags:
  - name: webserver
    referencePolicy:
      type: Source
